### ISSUE TITLE
about scaling

### ISSUE THREAD

**Issue by CoachingJane** [AndreKelm/RefineContourNet#7]
I found that you resize the the image to get richer data, but the gray value in contour-GT after scaling will no longer be 0 or 255, but between 0 and 255. Should the gray value in contour-GT be processed after scaling? For example:
contour-GT[contour-GT>=127.5] = 255
contour-GT[contour-GT<127.5] = 0?
or just do nothing.
thakn you!

**Comment by AndreKelm** [comment]
Hi,
What resizing do you mean? Is it part of the training or the evaluation? 

The network architecture itself has a reduction to half of the original image. This would be part of the training and could change the GT.

Do you mean the enlargement to restore the original image resolution? This would be part of the evaluation and a resizing of GT makes no sense anymore, because they have already the correct size.

**Comment by CoachingJane** [comment]
> Hi, What resizing do you mean? Is it part of the training or the evaluation?
> 
> The network architecture itself has a reduction to half of the original image. This would be part of the training and could change the GT.
> 
> Do you mean the enlargement to restore the original image resolution? This would be part of the evaluation and a resizing of GT makes no sense anymore, because they have already the correct size.

Im mean when you train the model, the data is augmented by random cropping, vertical flipping, and scaling between 0.7 and 1.3. when you scaling the image such as the original size is (300, 300), then you scaling to (400, 400), so your Contour-GT should scaling to (400, 400), is that true?

**Comment by AndreKelm** [comment]
Yes! That is correct! Hm, if the gray value of the contour GT is changed - then the change should be very small. If you want, you can investigate whether this small change has any effect on how the binary loss function interprets the contour GT. Because if there is no different treatment, then this small change will have no effect. But if not... 🧐

**Comment by CoachingJane** [comment]
> Yes! That is correct! Hm, if the gray value of the contour GT is changed - then the change should be very small. If you want, you can investigate whether this small change has any effect on how the binary loss function interprets the contour GT. Because if there is no different treatment, then this small change will have no effect. But if not... 🧐

I just use the code 
contour-GT[contour-GT>=127.5] = 255
contour-GT[contour-GT<127.5] = 0
to ensure data consistency, I don't know the difference between not using this code and using this code. I'll try it. 
thank you！
